using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Opium.Windows.UserControl.Library
{
        public class Icon :Control
        {

            public enum IconType
            {
                AutoGeneratedDoNotAmend
            }

            public static readonly DependencyProperty TypeProperty = DependencyProperty.Register(
                nameof(Type), typeof(IconType), typeof(Icon), new PropertyMetadata(default(IconType)));

            /// <summary>
            /// Gets or sets the name of icon being displayed.
            /// </summary>
            public IconType Type
            {
                get { return (IconType)GetValue(TypeProperty); }
                set { SetValue(TypeProperty, value); }
            }
        }
    }

